name: Fly Deploy
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Set secrets
          run: flyctl secrets set TOKEN="${{ secrets.TOKEN }}" && flyctl secrets set LOG_URL="${{ secrets.LOG_URL }}" && flyctl secrets set GUILD_ID="${{ secrets.GUILD_ID }}" && flyctl secrets set MODMAIL_GUILD_ID="${{ secrets.MODMAIL_GUILD_ID }}" && flyctl secrets set OWNERS="${{ secrets.OWNERS }}" && flyctl secrets set CONNECTION_URI="${{ secrets.CONNECTION_URI }}"
        - name: Deploy app
          run: flyctl deploy --remote-only
